api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /dynamic_conf.yml
    watch: true

log:
  level: DEBUG

accessLog: {}
